version: '3'
services:
  mfsmaster:
    image: johnymnemonic/rpi-lizardfs
    command: master
    restart: on-failure
    volumes:
      - /var/lib/lizardfs
  mfsmaster-shadow:
    image: johnymnemonic/rpi-lizardfs
    command: master
    restart: on-failure
    environment:
      MFSMASTER_PERSONALITY: shadow
    volumes:
      - /var/lib/lizardfs
  metalogger:
    image: johnymnemonic/rpi-lizardfs
    command: metalogger
    restart: on-failure
    volumes:
      - /var/lib/lizardfs
  chunkserver:
    image: johnymnemonic/rpi-lizardfs
    command: chunkserver
    restart: on-failure
    environment:
      # This lets you run the chunkserver with less available disk space
      MFSCHUNKSERVER_HDD_LEAVE_SPACE_DEFAULT: 20Mi # 4Gi is the default
      MFSHDD_1: /mnt/mfshdd
    volumes:
      - /mnt/mfshdd
  cgiserver:
    image: johnymnemonic/rpi-lizardfs
    command: cgiserver
    restart: on-failure
    ports:
      - 8080:80
  client1:
    image: johnymnemonic/rpi-lizardfs
    command: client /mnt/mfs
    restart: on-failure
    # Required permissions and devices for container to mount filesystem
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
  client2:
    image: johnymnemonic/rpi-lizardfs
    command: client /mnt/mfs
    restart: on-failure
    # Required permissions and devices for container to mount filesystem
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
